# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20200425_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.IntegerField(default=0, verbose_name='所在学院'),
        ),
    ]
