# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20200425_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans_authority',
            field=models.IntegerField(default=3, verbose_name='我的粉丝访问权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_authority',
            field=models.IntegerField(default=3, verbose_name='我的关注访问权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='publish_authority',
            field=models.IntegerField(default=3, verbose_name='我的发表访问权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='reply_authority',
            field=models.IntegerField(default=3, verbose_name='我的回复访问权限'),
        ),
    ]
