# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20200426_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.TextField(verbose_name='轮播图资源')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '轮播图信息',
                'verbose_name_plural': '轮播图信息',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
    ]
