# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_banner_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='hasRead',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
