# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 09:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_reply_hasread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='话题名称')),
                ('follow_num', models.IntegerField(default=0, verbose_name='话题关注人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '话题信息',
                'verbose_name_plural': '话题信息',
            },
        ),
        migrations.CreateModel(
            name='TopicFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注话题表',
                'verbose_name_plural': '用户关注话题表',
            },
        ),
        migrations.CreateModel(
            name='TopicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数')),
                ('is_boutique', models.BooleanField(default=False, verbose_name='是否为精品')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Topic', verbose_name='所属话题')),
            ],
            options={
                'verbose_name': '帖子信息',
                'verbose_name_plural': '帖子信息',
            },
        ),
        migrations.CreateModel(
            name='TopicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('hasRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Topic', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '回复信息',
                'verbose_name_plural': '回复信息',
            },
        ),
    ]
