# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_auto_20200504_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicreply',
            name='hasRead',
        ),
    ]
