# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0015_remove_topicreply_hasread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='hasRead',
        ),
        migrations.AddField(
            model_name='user',
            name='un_read_fans_num',
            field=models.IntegerField(default=0, verbose_name='未读粉丝数'),
        ),
        migrations.AddField(
            model_name='user',
            name='un_read_reply_num',
            field=models.IntegerField(default=0, verbose_name='未读回复数'),
        ),
    ]
