# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_auto_20200425_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivacy',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPrivacy',
        ),
    ]
