# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-03 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0005_usercollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollect',
            name='collect_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间'),
        ),
    ]
