# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0006_usercollect_collect_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='hasRead',
        ),
    ]
