# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-05 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersystem', '0008_face_userface'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='add_num',
            field=models.IntegerField(default=1, verbose_name='被用户添加次数'),
        ),
        migrations.AddField(
            model_name='face',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
    ]
