# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_boutique',
            field=models.BooleanField(default=False, verbose_name='是否为精品'),
        ),
    ]
