# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20200420_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
